<?php
/**
 * PassDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Team Pass API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * PassDetailTest Class Doc Comment
 *
 * @category    Class
 * @description PassDetail
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PassDetailTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PassDetail"
     */
    public function testPassDetail()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "gate"
     */
    public function testPropertyGate()
    {
    }

    /**
     * Test attribute "seat"
     */
    public function testPropertySeat()
    {
    }

    /**
     * Test attribute "section"
     */
    public function testPropertySection()
    {
    }

    /**
     * Test attribute "ticket_holder"
     */
    public function testPropertyTicketHolder()
    {
    }

    /**
     * Test attribute "event_reference"
     */
    public function testPropertyEventReference()
    {
    }

    /**
     * Test attribute "template_reference"
     */
    public function testPropertyTemplateReference()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "pkpass"
     */
    public function testPropertyPkpass()
    {
    }

    /**
     * Test attribute "jwt"
     */
    public function testPropertyJwt()
    {
    }

    /**
     * Test attribute "pass_created_at"
     */
    public function testPropertyPassCreatedAt()
    {
    }

    /**
     * Test attribute "pass_updated_at"
     */
    public function testPropertyPassUpdatedAt()
    {
    }
}
